version: "3"

services:
  currency_api_db:
    image: "postgres"
    container_name: "currency_api_db"
    restart: always
    environment:
      - POSTGRES_USER=secretdbuser
      - POSTGRES_PASSWORD=secretdbpass
      - POSTGRES_DB=currency_api_db
    ports:
      - "5432:5432"
    # volumes:
      # - ./postgres-data:/var/lib/postgresql/data