version: "3"

services:
  currency_api_db:
    image: "postgres"
    container_name: "currency_api_db"
    restart: always
    environment:
      - POSTGRES_USER=secretdbuser
      - POSTGRES_PASSWORD=secretdbpass
      - POSTGRES_DB=currency_api_db
    ports:
      - "5432:5432"
    # volumes:
      # - ./postgres-data:/var/lib/postgresql/data
  
  currency_api:
    build: .
    container_name: "currency_api"
    restart: always
    environment:
      - DB_HOST=currency_api_db
      - DB_PORT=5432
      - DB_USER=secretdbuser
      - DB_PASS=secretdbpass
    ports:
      - "9988:9988"